title: Civil Service Club
url: https://csc.sg
favicon: /images/csc-logo.png
colors:
  primary-color: "#9b1a3e"
  secondary-color: "#323232"
  media-colors:
    - title: media-color-one
      color: "#301818"
    - title: media-color-two
      color: "#c52327"
    - title: media-color-three
      color: "#301818"
    - title: media-color-four
      color: "#c52327"
    - title: media-color-five
      color: "#301818"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d19cj5vlg8czrw.amplifyapp.com
prod: https://master.d19cj5vlg8czrw.amplifyapp.com
facebook-pixel: ""
resources_name: events
shareicon: /images/csc-logo.png
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
